// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUOIEEMaZFP8a6CYLU4fLRH8UsEpWfCF8',
    appId: '1:1024198224621:web:4f02a8833055a66c09fae4',
    messagingSenderId: '1024198224621',
    projectId: 'stream-cdb37',
    authDomain: 'stream-cdb37.firebaseapp.com',
    storageBucket: 'stream-cdb37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5HSAw1lrD5KrHSpM-dPq1mH3zlmZjFgM',
    appId: '1:1024198224621:android:27a13f8db22b68ae09fae4',
    messagingSenderId: '1024198224621',
    projectId: 'stream-cdb37',
    storageBucket: 'stream-cdb37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrgT812FZIav4Tb1K0C7k2KHqO9PEeJWU',
    appId: '1:1024198224621:ios:78aa40c5a89a032e09fae4',
    messagingSenderId: '1024198224621',
    projectId: 'stream-cdb37',
    storageBucket: 'stream-cdb37.appspot.com',
    iosClientId: '1024198224621-nhm5moos03l6ct35qjps5vaa1r7423cb.apps.googleusercontent.com',
    iosBundleId: 'com.example.stream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrgT812FZIav4Tb1K0C7k2KHqO9PEeJWU',
    appId: '1:1024198224621:ios:0a372c00fe8bdff509fae4',
    messagingSenderId: '1024198224621',
    projectId: 'stream-cdb37',
    storageBucket: 'stream-cdb37.appspot.com',
    iosClientId: '1024198224621-q3pnf1isnr20bll6idgaelvibrgr7fk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.stream.RunnerTests',
  );
}
